version: '3'
services:
#mssql docker
  jobsearch-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Enterprise
    ports:
      - 1401:1433
    networks:
      - jobsearchnet

  jobsearch-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:JobSearch=Server=jobsearch-sql,1433;Database=JobSearchDocker;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 44399:80
    networks:
      - jobsearchnet      
    links:
      - jobsearch-sql
    depends_on:
      - jobsearch-sql
      
networks:
  jobsearchnet:
    driver: bridge  